### PR TITLE
make wise m/r job read last ten minutes of data

### PR DESCRIPTION
**Pull request by anew**
This changes the Wise map/reduce job, not to use a dataset to keep track of when it last ran. Instead, because this mr is run every 10 minutes as part of a workflow schedule, it will always read the last ten minutes leading up to the logical start time of the workflow. 

I think this is nicer because it simplifies the app and it also illustrates the getLogicalStartTime() feature of the MR context.

### CODE REVIEW

**Comment by abaranau** [comment]
The change is fine to me. It will make the implementation "less real" - i.e. it'll not handle failures and other "downtimes" well, etc. But ok for the example app

**Comment by anew** [comment]
Not sure what you mean. The M/R job always overwrites the previous bounce counts with the counts from its current run. So these counts always reflect only the last ten minutes anyway. I thought that was the intention.

**Comment by anew** [comment]
Oh now I get it. The BounceCountStore has a "write" method that actually increments. Is that confusing?

**Comment by abaranau** [comment]
I mean if mr job failed couple times - it will not re-attempt to precess data again? only last 10 min

**Comment by anew** [comment]
Yes right, it will always only process the last ten minutes. I was under the impression that that was the intention anyway - to compute the bounce counts of the last ten minutes. 

But now I realized that the dataset's write method is not a write but an increment, and it is actually accumulating the counts across runs. That means with this change we will drop the counts if the job fails, because we will not start where the last successful run took off. 

Is this change still ok then?

**Comment by abaranau** [comment]
I think it is OK

**Comment by anew** [comment]
OK, will merge it.

**Comment by anew** [comment]
The other option is to keep the lastRun dataset, and still use the getLogicalTime() to show that feature.  Opinions?

**Comment by abaranau** [comment]
I am fine with either. One is simpler another one is more correct :)

**Pull request merged**
