### PR TITLE
Removed service class

### PR DESCRIPTION
**Pull request by rohitsinha54**
Remove the Service definition class

### CODE REVIEW

**Comment by abaranau** [comment]
LGTM. Can we make it mergeable?

**Comment by abaranau** [comment]
do we need to update README?

**Comment by awholegunch** [comment]
The README should be updated to change:

\* A ``Service`` to store ``movies`` in a ``Dataset``

to include a description of each of the services:

\* A ``Service`` to store ``movies`` in a ``Dataset``
* A ``Service`` to recommend movies to a user

**Comment by awholegunch** [comment]
Actually, looks like this was already done. Please ignore my comment!

**Pull request closed without merging**
