### PR TITLE
CDAP-4251 Move to new configurer API

### PR DESCRIPTION
**Pull request by gokulavasan**
http://builds.cask.co/browse/CA-MAUT1-1
http://builds.cask.co/browse/CA-NAUT0-1
http://builds.cask.co/browse/CA-TAUT0-1
http://builds.cask.co/browse/CA-WAUT0-1

### CODE REVIEW

**Comment by bdmogal** [comment]
:+1:

**Comment by gokulavasan** [comment]
thanks @bdmogal. Will merge after builds pass

**Comment by gokulavasan** [comment]
@bdmogal Please review the last commit. Builds passed. Will squash and merge after your review.

**Comment by bdmogal** [comment]
:+1:

**Pull request merged**
