### PR TITLE
Fix compilations errors and miscellanous other cleanup.

### PR DESCRIPTION
**Pull request by awholegunch**
Replacement PR for https://github.com/caskdata/cdap-apps/pull/97

### CODE REVIEW

**Comment by anwar6953** [comment]
Lgtm since it's the same diff as
https://github.com/caskdata/cdap-apps/pull/97
And that got a lgtm

**Comment by gsps1** [comment]
:-1:  - StreamWriter was removed as a part of this PR - https://github.com/caskdata/cdap/pull/4191/ which was merged into 3.3 branch. cdap-3.2-compat branch works fine without this change.

**Comment by awholegunch** [comment]
@gsps1 Are you saying that this PR is not needed for the release/cdap-3.2-compatible branch?

**Comment by awholegunch** [comment]
@anwar6953 If this PR is not needed, let me know and I will close it, and you can merge the other one.

**Comment by gsps1** [comment]
yeah, this is not needed, @anwar6953 can confirm.

**Comment by anwar6953** [comment]
Just tried TwitterSentiment on release/cdap-3.2-compatible branch, and it works fine.
I'm ok with closing this PR, as it might be useful to replace deprecated methods, but not necessary.

**Pull request closed without merging**
