### PR TITLE
Wise: package name change in script

### PR DESCRIPTION
**Pull request by rohitsinha54**
Changed the package name in the scripts to be consistent with changes in pom.xml done in this commit: 
https://github.com/caskdata/cdap-apps/commit/933f60b28e78ba90a79e07a957827d801a8b3b61

This was making script commands of readme to fail.

### CODE REVIEW

**Comment by rohitsinha54** [comment]
@anew @chtyim: Please review. Thanks.

**Comment by sreevatsanraman** [comment]
the branch called hotfix/wise-script. Did you intend to merge this to release/2.5.0? If so was it branched correctly to begin with?

**Comment by rohitsinha54** [comment]
On release/2.5.0 its:
<artifactId>Wise</artifactId>

It changed on develop so I am trying to fix the script on develop accordingly.

Do you mean that only branches which change something in release should be prefixed by hotfix ?

**Comment by rohitsinha54** [comment]
@jguery : Is this thing fixed in some other PR or should this PR be merged ?

**Comment by rp-julienguery** [comment]
Yes it just got merged in another PR - https://github.com/caskdata/cdap-apps/pull/31.

**Comment by rohitsinha54** [comment]
Oh Okay. I will close this PR then.

**Pull request closed without merging**
