### PR TITLE
Fix compilations errors and miscellaneous other cleanup.

### PR DESCRIPTION
**Pull request by anwar6953**
The cdap-apps repo had gone outdated. Even though methods were deprecated in a previous release, the relevant code in these apps were not updated.
So, when the deprecated APIs got removed, these apps' test cases no longer compiled.

This Pull Request updates these apps to use the newer APIs and also does additional cleanup.

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
LGTM

**Comment by awholegunch** [comment]
This should first be merged to the release/cdap-3.2-compatible branch, and then merged to develop...
NLGTM....
:-1:

**Comment by awholegunch** [comment]
I've created a replacement PR for this: https://github.com/caskdata/cdap-apps/pull/98
I've now closed this. See my next comment.

**Comment by awholegunch** [comment]
:+1: Based on Ali's email, I thought that he was referring to changes that had gone in to 3.2.0. But that was not the case, as the changes were made in 3.3.0 (develop) and so this should go into develop.
If anything should happen, it's that the default branch for these repos should change from develop to the current release, so people don't start by building the wrong version...

**Comment by anwar6953** [comment]
Agreed. With @awholegunch 's last comment.

**Pull request merged**
