### PR TITLE
Fixed scripts to refer to the correct name of the MapReduce program.

### PR DESCRIPTION
**Pull request by sagarkapare**

### CODE REVIEW

**Comment by bdmogal** [comment]
LGTM. Do we have to do anything else to make this change available?

**Comment by rp-julienguery** [comment]
:+1:

**Comment by sagarkapare** [comment]
I think this also needs to go in release/cdap-2.7.0-compatible? Will check with @albertshau

**Comment by sagarkapare** [comment]
Closing this PR opening against release/cdap-2.7.0-compatible.

**Pull request closed without merging**
